### ISSUE TITLE
Keep getting DeprecationWarning when running zscroll

### ISSUE THREAD

**Issue by maplepy** [noctuid/zscroll#18]
```
/sbin/zscroll:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
```

**Comment by maplepy** [comment]
For your information I'm running the example script in the readme

	zscroll --before-text "♪ x" --delay 0.3 \
			--match-command "playerctl status" \
			--match-text "Playing" "--before-text ' '" \
			--match-text "Paused" "--before-text ' ' --scroll 0" \
			--update-check true "playerctl metadata --format '%{T2}{{ artist }} - %{T5}{{ title }}'"

**Comment by Wolfdesroyer8** [comment]
Yeah i'm having the same problem

**Comment by noctuid** [comment]
Try it now.
