### ISSUE TITLE
AUR package is broken

### ISSUE THREAD

**Issue by gldtn** [noctuid/zscroll#20]
fetching devel info...
error: failed to lookup: zscroll-git: fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

==> Making package: zscroll-git 0.1.r5.gd42dc2c-1 (Wed 16 Mar 2022 07:01:31 AM EDT)
==> Retrieving sources...
  -> Cloning zscroll git repo...
Cloning into bare repository '/home/gldtn/.cache/paru/clone/zscroll-git/zscroll'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
==> ERROR: Failure while downloading zscroll git repo
    Aborting...
error: failed to download sources for 'zscroll-git-0.1.r5.gd42dc2c-1':
error: packages failed to build: zscroll-git-0.1.r5.gd42dc2c-1

**Comment by noctuid** [comment]
Thanks, it should be fixed now. If you installed with an aur helper that caches things, you may need to build without the cache.
