### ISSUE TITLE
Would it be possible to add an argument to buffer the command output?

### ISSUE THREAD

**Issue by krinistof** [noctuid/zscroll#6]
I have a weather scrpit, that gets the data from an API

Every time the scrolling happens it calls the script. I would like to tell the program to catch the prev output, and by a given interval check for it. If you think that this is too specific problem, i would tell you, that this could save some resource by calling the script less than necessary. Untill your answer I will update the weather script for catching, but in my opinion that could be useful for others than me.

Thanks for your work!

**Comment by noctuid** [comment]
I think that's a perfectly reasonable use case. I've added a `-U` / `--update-interval` flag that you can use to specify how often update commands should be called (e.g. `zscroll -U 2 ...` to only check for new data every ~2 seconds). Please test.
